AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Lint/ScriptPermission:
  Enabled: false

Metrics/MethodLength:
  Max: 20
